name: Build 'master' Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cppcheck-docker-gitlab:latest
    - name: Authenticate into Docker Hub
      run: docker login docker.pkg.github.com -u jmrserver -p "$NEKOT_BUH_REKCOD"
      env:
        NEKOT_BUH_REKCOD: ${{ secrets.NEKOT_BUH_REKCOD }}
    - name: Push the Docker image into Docker Hub
      run: docker push docker.pkg.github.com/jmrserver/cppcheck-docker-gitlab/cppcheck-docker-gitlab:latest
